### PR TITLE
Fixed checking contentType

### PR DESCRIPTION
**Pull request by dankito**
Should be check of baseContentType that way round?

baseContentType is e.g. 'application/json'
accept is e.g. 'multipart/related, application/json'

### CODE REVIEW

**Comment by hideki** [comment]
Hi @dankito,
Thank you very much for your PR.
Have you ever singed [Couchbase contribute license agreement](https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement)? If not, can you sign it?

**Comment by dankito** [comment]
Just did that.
But really thought twice if i should sign such a hard to understand licence agreement.
Of course you can have the intellectual property of my contributions, but couldn't you formulate it shorter in a few terms, easier to understand also for non native English speakers?
Kind regards,
Christian Dankl

On 29/08/16 19:15, Hideki Itakura wrote:

Hi @dankito<https://github.com/dankito>,
Thank you very much for your PR.
Have you ever singed Couchbase contribute license agreement<https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement>? If not, can you sign it?

**Comment by hideki** [comment]
@dankito 
Thanks for signing agreement.
We will merge your PR into master branch as soon as we released `1.3.1`.

**Comment by hideki** [comment]
HI @dankito,
I merged your PR. Thank you very much for your contributions!

**Pull request merged**
