### PR TITLE
find the right attachment based on revpos. fixes #677

### LINKED ISSUE #677: Pulling attachments fail if document got a deleted revision in history
To reproduce:

create a pull replication to a couchdb (1.6.1 in my case)

1. insert a document containing an attachement (rev: 1-x)
2. pull replicate
3. delete the document (rev: 2-x)
4. pull replicate
5. insert the document again, containing the same attachment.(rev: 3-x)
6. pull replicate

The replication from step 6 will query couchdb with atts_since=2-x and couchdb will answer with an _attachment stub containing revpos: 1

CBL inserts the revision (3-x) into the revs table and tries to get the attachment from the parent sequence (2-x).
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L2967

This fails, since the deleted revision doesn't contain the attachment.

When I take a look at the attachments table of sqlite I find the attachment for rev 1-x is there.

I'm not sure what the best way would be to fix this.
Maybe an additional step to find the attachment by the given revpos, somewhere around here: https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L4471-L4478?

### PR DESCRIPTION
**Pull request by saubaer**
See https://github.com/couchbase/couchbase-lite-java-core/issues/677#issuecomment-122527475 for an updated description on how to reproduce.

(already signed the contributers agreement)

### CODE REVIEW

**Comment by hideki** [comment]
Hi @saubaer,
Thank you very much for sending us your PR.
Have you ever signed [Contributor License Agreement](https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement)? If not, could you please sign it? 
Note: Currently Google OAuth does not work for our license agreement page. Please use other provider such as yahoo?
Thanks.
Hideki

**Comment by hideki** [comment]
@saubaer, Is it possible to write unit test for this issue?

**Comment by saubaer** [comment]
Hi Hideki,

I signed the CLA for the other PR I did:

https://github.com/couchbase/couchbase-lite-java-javascript/pull/10

Hope they aren't needed on a repository Base :-)

Will see about unit tests, might take two or three days.

**Comment by hideki** [comment]
@saubaer Thank you for signing the agreement.

**Comment by hideki** [comment]
Hi @saubaer,

Sorry for late reply. We recently update database architecture to remove "attachments" table from SQLite database. For this change, we updated many attachment related codes, and it made your PR not merge-able. 

I tested if master branch code works well with error scenario you wrote in the ticket (https://github.com/couchbase/couchbase-lite-java-core/issues/677#issuecomment-122527475). But I could not reproduce it. Do you have a chance to test with latest master branch?

Thanks,
Hideki

**Comment by hideki** [comment]
HI @saubaer,
I'd like to address this issue with this way: https://github.com/couchbase/couchbase-lite-java-core/pull/698 , because of recent architecture change.
Thank you very much for your contributions!
I will close this PR.
Hideki

**Pull request closed without merging**
