### PR TITLE
Fixed #602 Make / db names work in windows

### LINKED ISSUE #602: Make / db names work in windows
Problem:
CBL Java Core replace forward slash "/" with colon ":". But colon is illegal character for Windows file system. 
https://github.com/couchbase/couchbase-lite-java-core/blob/e22ce2955563c4c26bdfbdfaeabed580b41b060a/src/main/java/com/couchbase/lite/Manager.java#L417-L422

Solution:
Instead, use period ".".

Reference: https://github.com/couchbase/couchbase-lite-java-core/pull/209

### PR DESCRIPTION
**Pull request by hideki**
- Use period "." instead of ":" for Windows platform

### CODE REVIEW

**Comment by pasin** [comment]
Have you had a chance to test the fix on a Windows machine?

**Comment by hideki** [comment]
No. Do you have Windows environment?

**Comment by pasin** [comment]
Just chat with @ashvindersingh, and @ashvindersingh can provide an access to a Windows VM.

**Comment by hideki** [comment]
Thanks!

**Comment by pasin** [comment]
https://issues.couchbase.com/browse/CBIT-2373

**Pull request merged**
