### PR TITLE
add configuration options for storageType for REST API

### PR DESCRIPTION
**Pull request by swaheed2**
accept optional body for do_PUT_Database with storageType as key.

Example:
```

var data = {
	storageType : "ForestDB"
	//ForestDB
	//SQLite
};
```

### CODE REVIEW

**Comment by hideki** [comment]
Hi @swaheed2,
API change is for cross-platform item. We need to talk with other platform engineers. Please wait for a while.

**Comment by swaheed2** [comment]
No problem.

FYI. I tested it on Android using these steps and it works: (https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin/issues/79)

**Comment by hideki** [comment]
Additional comment from team member:
- Do we need to support encryption?

**Comment by hideki** [comment]
Hi @swaheed2
We are internally working for  this item.  API could be different from  you proposed. We will track this item [here](#1444). So I will closed this PR.
Thank you for your contributions!

**Pull request closed without merging**
