### PR TITLE
NPE when running async query on all documents

### PR DESCRIPTION
**Pull request by biokys**
Using the latest maven repo version 1.4.0

It throws NullPointerException when try to query asynchronously over all the documents.

### CODE REVIEW

**Comment by hideki** [comment]
@biokys thanks for the PR offer. Can you please sign our Contributor License Agreement?

Sorry about the hassle, we just need to do this to protect against someone contributing code and then suing us for copyright infringement.

**Comment by tleyden** [comment]
@biokys it's here: https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement

**Comment by hideki** [comment]
@biokys 
Did you sign the agreement? Please let us know.

**Comment by biokys** [comment]
Yep, i did it now ;-)

**Comment by hideki** [comment]
Hi @biokys
Thanks for your PR.  We merged your PR.
I wonder what makes view variable null.
If possible, could you  please share code snippet to reproduce this or write small test case?
Thanks!

**Pull request closed without merging**
