### PR TITLE
Update REST API to support Stopped, Idle and Offline states and continuous, longpoll responses

### PR DESCRIPTION
**Pull request by deefactorial**
This update will update the active_tasks API to support the features needed to find out the states of the replication as well as the ability to get continuous and longpoll responses from the active_tasks API.

### CODE REVIEW

**Comment by hideki** [comment]
@andreibaranouski Could you please run functional test to this PR? If it pass, could you please assign to me?

**Comment by andreibaranouski** [comment]
@hideki I run cblite-tests against couchbase-lite-android-liteserv(master) + pr 
there are no any regressions in the results

**Comment by hideki** [comment]
@andreibaranouski  Thank you very much!

**Comment by hideki** [comment]
@deefactorial Thank you very much for your contributions!

**Comment by deefactorial** [comment]
I hope is serves those that use it well. I was able to implement cloud status icon in my app with this PR.

**Pull request merged**
