### PR TITLE
Fixed Android Issue 863 - LiveQuery is blocked by replicator

### PR DESCRIPTION
**Pull request by hideki**
This commit is second step to fix issue 863: replicator own own executor service instead of using workExecutor.

Area needs your attention: 
- With this commit, the executor is shutdown in `finalize()` of `ReplicationInternal`. I am not 100% sure if it is ok. Ideally `ExecuterService.shutdown()` should be called out-side of GC.
- If app keeps creating new Replicator, thread leak is caused till app close Database because database holds all replicators which also hold ReplicationInternal.

### CODE REVIEW

**Comment by pasin** [comment]
I don't have any comments. Can I merge this one before the other one?

**Comment by hideki** [comment]
yes

**Comment by pasin** [comment]
Can you fix the conflict?

**Comment by hideki** [comment]
Fixed conflict.

**Pull request merged**
