### PR TITLE
Needed for the ability to mock the database, for test purposes

### PR DESCRIPTION
**Pull request by ryankennedyio**
We need this ability for unit testing in Android Studio.

We were hoping to be able to create actual databases only using the JVM, but got UnsupportedOperationException when attempting to create a Manager() without parameters (e.g. the Android independant version).

Simply mocking the databases is our next best step for now, in light of a non-Android implementation of databases not yet being available.

### CODE REVIEW

**Comment by ryankennedyio** [comment]
@tleyden @zgramana 

Some context behind why I made the PR:
https://forums.couchbase.com/t/feature-request-why-is-document-a-final-class/2548

**Comment by hideki** [comment]
Hi @ryankennedyio,
Have you ever signed the contributor license agreement?
https://github.com/couchbase/couchbase-lite-ios/wiki/Sign-the-contributor-license-agreement
Thanks.

**Comment by ryankennedyio** [comment]
Sorry @hideki, I've tried twice but am unable to.
I don't use any of the other supported OpenID 2.0 services.
Any alternatives ?

screen shot 2015-07-14 at 7 24 27 am

**Comment by hideki** [comment]
Hi @ryankennedyio,
Sorry for signing problem. It is known issue for a while since Google stopped OpenID 2.0.

Alternatives are signing with other provider like Yahoo. Or can you send me scanned document after sign?

Sorry for your inconvinece.

**Comment by ryankennedyio** [comment]
Sorry @hideki for wasting your time with this.
I signed up to a Yahoo account & submitted the agreement just now.

**Comment by tleyden** [comment]
@ryankennedyio thanks!  We are working on reducing the friction here .. thanks for sticking with it.

**Pull request merged**
