### PR TITLE
Fixed couchbase/couchbase-lite-android/issues/846

### PR DESCRIPTION
**Pull request by ashihaby**

### CODE REVIEW

**Comment by hideki** [comment]
Hi @ashihaby,
Thank you very much for your PR. I have question. Do you have any issues with default SQLite encoding? Could you please provide background of this PR?
Thanks!

**Comment by ashihaby** [comment]
@hideki I have the same issue that has been mentioned here couchbase/couchbase-lite-android#846.
I was receiving SQLiteDatabaseCorruptException, when emit keys that has NON-ASCII characters.

**Comment by hideki** [comment]
@ashihaby Thank you very much for your input!

**Comment by hideki** [comment]
Hi @ashihaby,

1. SQLite supports two encoding types. UTF-8 and UTF-16. I believe default is UTF-8. Do you think default is not UTF-8?

2. I run the test which was provided by @kombadzomba with your fix. https://github.com/couchbase/couchbase-lite-android/issues/846#issuecomment-222009529  However this fix can not solve the issue.
Test codes: https://github.com/couchbase/couchbase-lite-android/commit/fbde5d774a05a338afe861de2f00da7838aded0b

I have a question and a request:
- Do you see any Android device that default SQLite encoding is UTF-16 (non-UTF-8)?
- Can you write simple unit test that causes SQLiteDatabaseCorruptException? You can copy&paste https://github.com/couchbase/couchbase-lite-android/commit/fbde5d774a05a338afe861de2f00da7838aded0b and change the value could be good enough.

Thanks!

**Comment by hideki** [comment]
Hi @ashihaby,
I believe SQLite's default encoding is `UTF-8`. Currently I guess this is not direct fix for couchbase/couchbase-lite-android#846. 
I will close this PR.
Thank you very much for all your contributions!

**Pull request closed without merging**
