### PR TITLE
Encoding of doc ids in replication

### LINKED ISSUE #600: Push replication to rcouch fails on rev with attachments
The problem seems to be caused by `PusherInternal#uploadMultipartRevision(RevisionInternal)` as its the only method that calls a StringBody constructor capable of getting an NPE latter on.

Stacktrace:
```
Exception uploading multipart request
java.lang.NullPointerException: Attempt to get length of null array
	at com.couchbase.org.apache.http.entity.mime.content.StringBody.getContentLength(StringBody.java:183)
	at com.couchbase.org.apache.http.entity.mime.MultipartEntity.isRepeatable(MultipartEntity.java:139)
	at com.couchbase.org.apache.http.entity.mime.MultipartEntity.isChunked(MultipartEntity.java:147)
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:84)
	at org.apache.http.protocol.BasicHttpProcessor.process(BasicHttpProcessor.java:295)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:413)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:183)
	at com.couchbase.lite.support.RemoteMultipartRequest.run(RemoteMultipartRequest.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by sergio91pt**
- Encode document id in uploadMultipartRevision
- Avoid encoding the slash of design documents
- Fix attachment filenames in multipart uploads

Closes #600, #615

### CODE REVIEW

**Comment by hideki** [comment]
Hi @sergio91pt  Thank you very much for your PR. I did not recognize this PR by now. Please give me few days to review.

**Comment by hideki** [comment]
Hi @sergio91pt,

Can you do `git rebase` instead of `merge` for d0e2b5d? Or I can `git cherry pick` for previous three commits.

**Comment by sergio91pt** [comment]
@hideki Sorry about that. I created a new PR (#627) of a rebased branch.
I'm gonna close this one.

**Comment by hideki** [comment]
@sergio91pt, Thank you for new PR. Codes are look good. After I run the test, I will merge your PR. Thanks a lot!

**Pull request closed without merging**
